name: Docker Image CI

on:
  push:
    branches: [ "FB-DEV-Feature-EVera" ]
  pull_request:
    branches: [ "FB-DEV-Feature-EVera" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
    # 1. Clonar el repositorio
    - name: Check out the repository
      uses: actions/checkout@v4

    # 2. Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Limpiar caché de dependencias y actualizar dependencias
    - name: Build with Maven and Update Dependencies
      run: mvn clean install -U

    # 4. Ejecutar las pruebas
    - name: Run tests
      run: mvn test
      
    # 5. Publicar los resultados de las pruebas si fallan
    - name: Upload Surefire Reports
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: real-time-notifications-microservice/target/surefire-reports

  # Opción 6: Si necesitas desactivar las pruebas temporalmente
  skip_tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Check out the repository
      uses: actions/checkout@v4

    # 2. Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    # 3. Desactivar las pruebas y construir el JAR
    - name: Build without tests
      run: mvn clean package -DskipTests
