name: Docker Image CI

on:
  push:
    branches: [ "FB-DEV-Feature-EVera" ]
  pull_request:
    branches: [ "FB-DEV-Feature-EVera" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0.14
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
          
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set environment variables
      run: echo "MONGO_URI=mongodb://localhost:27017/real-time-notifications" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install
      env:
        MONGO_URI: ${{ env.MONGO_URI }}  # Pasa la variable MONGO_URI al proceso Maven

    - name: Run tests
      run: mvn test
      env:
        MONGO_URI: ${{ env.MONGO_URI }}  # Pasa la variable MONGO_URI al proceso Maven

    - name: Build Docker image
      run: docker build -t ghcr.io/whoisvera/my-app:${{ github.sha }} -f real-time-notifications-microservice/src/Dockerfile .

    - name: Push Docker image
      run: docker push ghcr.io/whoisvera/my-app:${{ github.sha }}

    - name: Upload Surefire Reports
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/surefire-reports/
